[package]
name = "globe_render"
version = "0.1.0"
edition = "2021"

[dependencies]
alvidir.workspace = true
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bytemuck = "1.17"
globe-rs.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "globe-app"
path = "src/main.rs"
